#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "open-elevation"
name = "Open-Elevation"
description.en = "A free and open-source elevation API."

version = "2021.16.09~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "GPL-2.0"
website = "https://open-elevation.com/"
demo = "https://api.open-elevation.com/"
admindoc = "https://github.com/Jorl17/open-elevation/blob/master/docs/host-your-own.md#without-docker"
code = "https://github.com/Jorl17/open-elevation"

fund = "https://open-elevation.com/"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = "all"
multi_instance = true


ldap = "not_relevant"
sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/Jorl17/open-elevation/archive/677f9de1b6c1a10b48028f36e072bf8b6ba19b9e.tar.gz"
    sha256 = "508d1138f8d8ae7e9e6238630a46512d80908e5303394fff7f2d79ee09e38b54"

    autoupdate.strategy = "latest_github_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-venv, gdal, libspatialindex-dev, unrar-free, bc"
