#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"


#=================================================
# APP CONFIG FILES
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_safe_rm "$install_dir/config.ini"
ynh_config_add --template="config.ini" --destination="$install_dir/config.ini"

#=================================================
# INSTALL PYTHON DEPENDENCIES
#=================================================
ynh_script_progression "Installing Python dependencies..."

pushd "$install_dir"
    # Needed for gdal to be able to build
    export CPLUS_INCLUDE_PATH=/usr/include/gdal
    export C_INCLUDE_PATH=/usr/include/gdal

    ynh_exec_as_app python3 -m venv "$install_dir/venv"
    ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install --upgrade pip numpy bottle gunicorn lazy numpy Pillow Rtree


    #ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install -r "$install_dir/requirements.txt"

    #ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" uninstall web3.py
    #ynh_hide_warnings ynh_exec_as_app "$install_dir/venv/bin/pip" install git+https://github.com/ethereum/web3.py.git

    ynh_safe_rm "$install_dir/.cache/pip"
popd

#Logrotate has to be added now, because the app won’t start if there are no logs files
ynh_config_add_logrotate
touch /var/log/$app/$app.log
chown -R $app:www-data /var/log/$app/

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd --service="${app}"

yunohost service add "${app}" --description="Open-Elevation service" --log="/var/log/$app/$app.log"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd services..."

ynh_systemctl --service="${app}" --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
